image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

services:
  - docker

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up -d
  - sleep 40
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass -jar ./artifacts/aqa-shop.jar &

build_script:
  - sleep 40
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true -Ddatabase.url=jdbc:mysql://localhost:3306/app -Ddatabase.name=app -Ddatabase.password=pass --info
